module.exports = [
  // Toradora
  {
    title: 'とらドラ! (とらドラ! [Toradora!] Light Novel #1)',
    author: 'Takemiya, Yuyuko',
    year: 2006,
    dateRead: 2017,
    rating: 10,
    comment: '',
  },
  {
    title: 'とらドラ! 2 (とらドラ! [Toradora!] Light Novel #2)',
    author: 'Takemiya, Yuyuko',
    year: 2006,
    dateRead: 2017,
    rating: 10,
    comment: '',
  },
  {
    title: 'とらドラ! 3 (とらドラ! [Toradora!] Light Novel #3)',
    author: 'Takemiya, Yuyuko',
    year: 2006,
    dateRead: 2017,
    rating: 10,
    comment: '',
  },
  {
    title: 'とらドラ! 4 (とらドラ! [Toradora!] Light Novel #4)',
    author: 'Takemiya, Yuyuko',
    year: 2007,
    dateRead: 2017,
    rating: 10,
    comment: '',
  },
  {
    title: 'とらドラ! 5 (とらドラ! [Toradora!] Light Novel #5)',
    author: 'Takemiya, Yuyuko',
    year: 2007,
    dateRead: 2017,
    rating: 10,
    comment: '',
  },
  {
    title: 'とらドラ! 6 (とらドラ! [Toradora!] Light Novel #6)',
    author: 'Takemiya, Yuyuko',
    year: 2007,
    dateRead: 2017,
    rating: 10,
    comment: '',
  },
  {
    title: 'とらドラ! 7 (とらドラ! [Toradora!] Light Novel #7)',
    author: 'Takemiya, Yuyuko',
    year: 2008,
    dateRead: 2017,
    rating: 10,
    comment: '',
  },
  {
    title: 'とらドラ! 8 (とらドラ! [Toradora!] Light Novel #8)',
    author: 'Takemiya, Yuyuko',
    year: 2008,
    dateRead: 2017,
    rating: 10,
    comment: '',
  },
  {
    title: 'とらドラ! 9 (とらドラ! [Toradora!] Light Novel #9)',
    author: 'Takemiya, Yuyuko',
    year: 2008,
    dateRead: 2017,
    rating: 10,
    comment: '',
  },
  {
    title: 'とらドラ! 10 (とらドラ! [Toradora!] Light Novel #10)',
    author: 'Takemiya, Yuyuko',
    year: 2009,
    dateRead: 2017,
    rating: 10,
    comment: '',
  },
  // Harry Potter
  {
    title: "Harry Potter and the Sorcerer's Stone (Harry Potter #1)",
    author: 'Rowling, J.K.',
    year: 1997,
    dateRead: 2002,
    rating: 10,
    comment: '',
  },
  {
    title: 'Harry Potter and the Chamber of Secrets (Harry Potter #2)',
    author: 'Rowling, J.K.',
    year: 1999,
    dateRead: 2002,
    rating: 10,
    comment: '',
  },
  {
    title: 'Harry Potter and the Prisoner of Azkaban (Harry Potter #3)',
    author: 'Rowling, J.K.',
    year: 1999,
    dateRead: 2003,
    rating: 6,
    comment: '',
  },
  {
    title: 'Harry Potter and the Goblet of Fire (Harry Potter #4)',
    author: 'Rowling, J.K.',
    year: 2000,
    dateRead: 2003,
    rating: 8,
    comment: '',
  },
  {
    title: 'Harry Potter and the Order of the Phoenix (Harry Potter #5)',
    author: 'Rowling, J.K.',
    year: 2003,
    dateRead: 2004,
    rating: 7,
    comment: '',
  },
  {
    title: 'Harry Potter and the Half-Blood Prince (Harry Potter #6)',
    author: 'Rowling, J.K.',
    year: 2005,
    dateRead: 2006,
    rating: 7,
    comment: '',
  },
  {
    title: 'Harry Potter and the Deathly Hallows (Harry Potter #7)',
    author: 'Rowling, J.K.',
    year: 2007,
    dateRead: 2007,
    rating: 7,
    comment: '',
  },
  // Темный лорд
  {
    title: 'Тёмный Лорд (Темный Лорд #1)',
    author: 'Прозоров, Александр',
    year: 2008,
    dateRead: 2012,
    rating: 9,
    comment: '',
  },
  {
    title: 'Темное пророчество (Темный Лорд #2)',
    author: 'Прозоров, Александр',
    year: 2009,
    dateRead: 2012,
    rating: 10,
    comment: '',
  },
  // Bartimaeus Sequence
  {
    title: 'The Amulet of Samarkand (Bartimaeus #1)',
    author: 'Stroud, Jonathan',
    year: 2003,
    dateRead: 2015,
    rating: 7,
    comment: '',
  },
  {
    title: "The Golem's Eye (Bartimaeus #2)",
    author: 'Stroud, Jonathan',
    year: 2004,
    dateRead: 2015,
    rating: 7,
    comment: '',
  },
  {
    title: "Ptolemy's Gate (Bartimaeus #3)",
    author: 'Stroud, Jonathan',
    year: 2005,
    dateRead: 2015,
    rating: 6,
    comment: '',
  },
  {
    title: '1984',
    author: 'Orwell, George',
    year: 1949,
    dateRead: 2016,
    rating: 10,
    comment: '',
  },
  {
    title: 'Twenty Thousand Leagues Under the Sea (Captain Nemo #1)',
    author: 'Verne, Jules',
    year: 1869,
    dateRead: 2001,
    rating: 8,
    comment: '',
  },
  {
    title: 'The Talking Parcel',
    author: 'Durrell, Gerald',
    year: 1975,
    dateRead: 2004,
    rating: 10,
    comment: '',
  },
  {
    title: "If Only It Were True (Et si c'était vrai #1)",
    author: 'Levy, Marc',
    year: 2000,
    dateRead: 2014,
    rating: 6,
    comment: '',
  },
  {
    title: 'Death Traps: The Survival of an American Armored Division in World War II',
    author: 'Cooper, Belton Y.',
    year: 1998,
    dateRead: 2016,
    rating: 8,
    comment: '',
  },
  {
    title: "Hellstrom's Hive",
    author: 'Herbert, Frank',
    year: 1973,
    dateRead: 2016,
    rating: 8,
    comment: '',
  },
  {
    title: 'Rich Dad, Poor Dad (Rich Dad #1)',
    author: 'Kiyosaki, Robert T.',
    year: 1997,
    dateRead: 2017,
    rating: 6,
    comment: '',
  },
  // Metro Book Series
  {
    title: 'Metro 2033 (Метро #1)',
    author: 'Glukhovsky, Dmitry',
    year: 2005,
    dateRead: 2006,
    rating: 10,
    comment: '',
  },
  {
    title: 'Metro 2034 (Метро #2)',
    author: 'Glukhovsky, Dmitry',
    year: 2009,
    dateRead: 2010,
    rating: 6,
    comment: '',
  },
];
